# 파일명: docker-compose.yml
version: '3.8'

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --innodb-buffer-pool-size=512M  # 8GB 램이라도 DB 제한은 두는 게 안전
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: smishing_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./ddl:/docker-entrypoint-initdb.d

  backend:
    build: .
    volumes:
    - ./src:/app/src  # <--- 이 줄이 핵심! (내 src 폴더를 도커랑 연결)  
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_URL: mysql+pymysql://user:password@db:3306/smishing_db
      GEMINI_API_KEY: "AIzaSyDXAqnb6826hQNaYYOKdp6NScOjPV1BD2Q"
      # 만약 키를 파일에 적기 싫으면 위 줄 지우고 실행할 때 환경변수로 넘기면 됩니다.

volumes:
  db_data:
